### ISSUE TITLE
Training with view fails for any dataset

### ISSUE THREAD

**Issue by kowsheek** [m-bemana/xfields#4]
Hi there, this is an amazing paper and was excited to try it.

I initially tried with a different dataset but got this error so I tried with the sample dataset and got the same results when trying to with type `view`.

I am getting a similar message when trying with `time` but it seems to run on the sample dataset and my own.

Happy to provide further information.

```
(base) C:\Users\k\Projects\brio\xfields>python train.py --dataset dataset/view/island  --type view  --dim 5 5 --factor 2 --num_n 2 --nfg 8 --sigma 0.5 --br 1 --savepath results/
WARNING:tensorflow:From C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\layers\core.py:39: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\layers\pooling.py:66: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

---------- Perform Training ----------
XField type: ['view']
Dimension of input xfield: [5, 5]
Dataset path: dataset/view/island
Downsampling factor: 2
Output resolution: 882 x 882
 Reading image 25 out of 25
 ------- Creating the model -------
Number of learnable parameters (decoder): 483042
------------ Start Training ------------
Starting learning rate with 0.0001
2021-01-30 22:27:40.012086: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] layout failed: Invalid argument: Unsupported tensor size: 2
Traceback (most recent call last):
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[3,32,882,882] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node gen_flows/layer_8/conv2d/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[3,32,882,882] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node gen_flows/layer_8/conv2d/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Mean/_27]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 338, in <module>
    run_training(args)
  File "train.py", line 282, in run_training
    learning_rate:lr,
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[3,32,882,882] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gen_flows/layer_8/conv2d/Conv2D (defined at C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\layers\convolution\simplified_conv.py:212) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[3,32,882,882] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gen_flows/layer_8/conv2d/Conv2D (defined at C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\layers\convolution\simplified_conv.py:212) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Mean/_27]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node gen_flows/layer_8/conv2d/Conv2D:
 gen_flows/layer_8/pad_layer (defined at C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\layers\padding.py:62)

Input Source operations connected to node gen_flows/layer_8/conv2d/Conv2D:
 gen_flows/layer_8/pad_layer (defined at C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\layers\padding.py:62)

Original stack trace for 'gen_flows/layer_8/conv2d/Conv2D':
  File "train.py", line 338, in <module>
    run_training(args)
  File "train.py", line 87, in run_training
    flows = Flow(inputs,h_res,w_res,num_output,args.nfg,min_,max_)
  File "C:\Users\k\Projects\brio\xfields\model.py", line 89, in Flow
    output = conv_layer(upsampled,num_filter,padding,3)
  File "C:\Users\k\Projects\brio\xfields\model.py", line 51, in conv_layer
    network = Conv2d(batch_input, n_filter=out_channels, filter_size=(fs,fs),strides=(1, 1), act=tf.nn.leaky_relu, padding='VALID',W_init=tf.random_normal_initializer(0, 0.02),b_init = tf.constant_initializer(value=0.0))
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\decorators\deprecated_alias.py", line 24, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorlayer\layers\convolution\simplified_conv.py", line 212, in __init__
    self.outputs = conv2d(self.inputs)  # must put before ``new_variables``
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 146, in wrapper
    ), args, kwargs)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 446, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 253, in _call_unconverted
    return f(*args, **kwargs)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 196, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1079, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 635, in __call__
    return self.call(inp, filter)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 234, in __call__
    name=self.name)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1953, in conv2d
    name=name)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\k\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by m-bemana** [comment]
Hi,

The error says you are getting Out of Memory, your GPU doesn’t have enough available memory.
you can for now alleviate this problem either by running on lower resolution (try factor 4)
or decrease the network capacity(try nfg 4)
